### PR TITLE
Updated to new tel.search.ch API http://tel.search.ch/api/help

### PR DESCRIPTION
**Pull request by sirtoobii**

### CODE REVIEW

**Comment by lgaetz** [comment]
I have confirmed the old version is broken and this one works for exactly one phone number. The TOS don't appear to have changed since I reviewed them in 2009, so I don't see any reason why this shouldn't be merged.

@tm1000 should it get merged to 2.11 branch?

**Comment by tm1000** [comment]
I need the contributor license agreement signed by this user: http://wiki.freepbx.org/display/DC/Code+License+Agreement

**Comment by sirtoobii** [comment]
I've sent the signed agreement to code@sangoma.com

**Comment by tm1000** [comment]
Agreement signed. Ready to merge.

**Pull request merged**
