### PR TITLE
Add new CapsuleCRM CID lookup module.

### PR DESCRIPTION
**Pull request by stianeklund**

### CODE REVIEW

**Comment by lgaetz** [comment]
Hey @stianeklund thanks for the contribution. All contributors must have a code submission agreement on file, have you already?
http://wiki.freepbx.org/display/FOP/Code+License+Agreement

**Comment by stianeklund** [comment]
@lgaetz Hi there, I've signed the agreement and emailed it just now. Thanks for the heads up, I wasn't aware of this.

**Comment by lgaetz** [comment]
Thanks. You are correct, this is a requirement of FreePBX. If you check other pull requests to this project you will see that others have also been requested to file.

As soon as @tm1000 confirms your paperwork is in order, I will handle the PR.

Thanks again.

**Comment by tm1000** [comment]
This is good to go @lgaetz

**Comment by stianeklund** [comment]
Hey @lgaetz I'm not familiar with the differences between 2.11 and 13.0, would this PR also possibly work with 13?

**Comment by tm1000** [comment]
Yes it will work in 13 fine.

**Comment by stianeklund** [comment]
@tm1000 Any reason this can't be merged into 12.0 and or 13? From what I can tell now this source will isn't in newer releases. Are there compatibility issues that I should look into & or resubmit a PR for this?

**Pull request merged**
