### PR TITLE
Google Contacts Beta 1

### PR DESCRIPTION
**Pull request by ntadmin**
This is the code I have working for integrating Google Contacts into Superfecta. It shouldn't interfere with any of the existing parts. Issue 210.

### CODE REVIEW

**Comment by tm1000** [comment]
Looks great :+1:

**Comment by ntadmin** [comment]
Cool.
Would it be sensible to start on work on a suggestion that go with this but involve other code in the system: The addition of 'internal' parameter types so that not all the run_params must be exposed to to the end user. Would require a new param type (change to ajax.inc) and a method for updatin parameter values (addition to the base class for source-XXXXXX)?

**Comment by tm1000** [comment]
@ntadmin sounds good to me. Just submit pull requests whenever you need. If there's something specific you need to know about message @lgaetz or I. @lgaetz and I work for the same parent company so we can both do what needs to be done.

**Comment by ntadmin** [comment]
Cool. I've followed both of you so I can find you again! I'm probably going to have to focus on a different aspect of the pbx for a while, but I expect to be back to superfecta. Getting multi working looks like an interesting challenge! I'll keep checking so I know what's going on.

**Pull request merged**
