### PR TITLE
Initial addition of Google Contacts to 12.0

### PR DESCRIPTION
**Pull request by ntadmin**
Adding the Google contact code to the 12.0 branch to distinguish it from other added improvements.

### CODE REVIEW

**Comment by lgaetz** [comment]
Finally got around to testing this .module with FreePBX 12 and it is working fine for me. I would suggest some minor adjustments to the online help messages which will follow in another post.

@ntadmin take a look at the [pushbullet module ](https://github.com/POSSA/Caller-ID-Superfecta/blob/release/2.11/sources/source-Send_to_PushBullet.module) specifically the `__construct()` function and see if that approach will work to make your GUI a bit cleaner.

**Comment by lgaetz** [comment]
Suggested edits for mouseover help, mainly because the debug routine in 12.x is no longer below the list of modules.

This is a one off code to authenticate superfecta to Google for you. How to set it: Once you've set your [Google] ID [in the field above] ~~(box above),~~ and ~~clicked submit to~~ save[ed] it, you ~~should click on~~ must run a debug. Further instructions will then be provided in the debug output ~~area below~~. Once you've followed [the link provided] ~~them~~, copy the code from the Google authentication page into [this field] ~~here~~ (replace the "XXX"). [Save again then run another debug]~~, click submit, and click debug below, having put a test number in the field below.~~

CHANGE AT YOUR PERIL, [this field will populate automatically after a successful authorization]. This is the day to day [authorization] ~~authorisation~~ code for the requests. If it is blank, there is an [authorization] ~~authorisation~~ issue.

**Comment by ntadmin** [comment]
I've had a look at the pushbullet code - are you suggesting using a file to store the information? That would make sense if ti didn't need to be updated on the fly, after calling __construct. As there is a well defined database in which the other parameters are stored, why not just create an 'internal' parameter type that isn't displayed but which the module can update? I'm working on some code for this and will push it through when I know it works.

**Comment by tm1000** [comment]
There is a hidden key value store in 12. Though not implemented in Superfecta as of yet. However you could store random stuff into the database table "admin". You'll notice it might already have some other values in it and was used as a poor mans key store since 2.5 or so.

**Comment by ntadmin** [comment]
Interesting.

Thinking about how best for superfecta to develop, which of the following is best:

1. Use the informal poor mans key table.

2. Use the hidden key store

3. Use the existing parameter system (which has resolved all issues of db access and ensuring no overlap between parameters from different methods) and extend it to allow 'internal' keys value pairs.

To me, but perhaps I'm wrong, it would make sense for each method within superfecta to declare both user set and internal to the method parameters in the param list at the top. That way:

a. All the parameters are clear for anyone working on the code to see; they aren't suddenly accessed in the middle of the code with no real definition save in the mind of the person who wrote the code.

b. Everything will be delivered to get_caller_id in the single run_params argument.

It is surprisingly easy to achieve this in the existing framework, and in a way that means that the source for each method doesn't need to know anything about the actual freepbx database.

**Comment by tm1000** [comment]
Whatever works best for you. I agree with what you have proposed and if you want to do it then more power to you :-D 

As for support. It's up to you if you like 12 better or 2.11. I would rather you focus on 12. But it's your time and I thank you very very much for it.

**Comment by ntadmin** [comment]
I'll work on 12.0, as it's the future!

I've just pushed through a proposed change to superfecta_single.php. I noted the the get method uses the data passed to the class to get the run_params for the source, but that the post method accessed the databse directly, using, it seemed to me, a method that was more in line with 11 than 12.

I've changed to post to use the same approach as get, thus avoiding DB access completely in superfect_single.

The next planned proposed changes will rely on superfecta_single not using the old (I think) database approach, so please flag if I've misunderstood here.

**Comment by ntadmin** [comment]
ps. This may (or may not) trash _multi, but as I think multi is currently disabled, I'm guessing that this is ok?

**Comment by tm1000** [comment]
Don't worry about multi too much. Whenever I get to it I'll fix it but I want to find a better way to do it first 

Sent from Outlook




On Thu, May 14, 2015 at 1:28 AM -0700, "ntadmin" <notifications@github.com> wrote:












ps. This may (or may not) trash _multi, but as I think multi is currently disabled, I'm guessing that this is ok?

**Comment by ntadmin** [comment]
ref commit f28c061:

Two changes

1. Allow sources to update parameters via the addition of the updateParameter($key, $new_value)  method to superfecat_base.php. This means that the source module does not need to know how the database is structured in order to update a parameter. To make this work, it was also necessary to change Superfecta.class.php to send $this->db rather than the global $db, which also seemed more consistent with the rest of the code.

2. Update Superfecta.class.php so that when an ajax triggered parameter update is called, it does not attempt to update parameters of type 'internal', as they wont be returned by the web page, as it wont have got them in the first place. Arguably the switch within ajax case 'options' block should have an explicit case 'internal' which does nothing, to protect against other defaults, but I haven't put this in.

**Comment by ntadmin** [comment]
OK, I think that's a block done there. Headlines:
 - Sources can now declare a parameter type 'internal' in the param list which is for their use only.
 - They can update that (and all of their) parameters by calling $this->updateParameter($key, $value)
 - In non-debug mode, superfecta_single now returns first real caller_id without going through whole source list.
 - Google Contacts works.

Caveats:
 - Google Contacts requires a key, which is currently set to one associated with my personal user. There may be use limitations on it, so commercial use of this module may require them to enter keys for themselves. To be investigated.
 - I haven't been able to test it against the other sources with any rigour.

**Comment by ntadmin** [comment]
Finally, can I thank you all for this fantastic module? It's been really easy to get my head around it and try to help out. And the speed increase in 12 is majestic!

**Comment by lgaetz** [comment]
> Finally, can I thank you all for this fantastic module? It's been really easy to get my head around it and try to help out. 

And thank you for your contributions, it is so satisfying (but rare) to have real contributions back from the community. I will test your latest changes as soon as I have a spare minute.

**Pull request merged**
