### PR TITLE
Canada411 only accepts HTTPS requests now

### PR DESCRIPTION
**Pull request by themurman**
I've just moved to HTTPS requests. Tests fine on my system

Regards

### CODE REVIEW

**Comment by lgaetz** [comment]
Thanks @themurman. 

This file never got any comments added to the top, it probably hasn't been touched in years. Go ahead and add the following then credit yourself however you want

```php
<?php

/**** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** *
 * Developer notes:
 *
 * 411.ca TOS details here: https://411.ca/pages/terms
 * Reviewed 2013-05-16 and found no language preventing superfecta usage
 * 
 * Releases:
 *
 * 2010-03-16		created for ver 2.2 by zorka
 * 2013-08-16		migrated to 3.x platform by lgaetz
 * 2015-05-21		url fix by themurman
 *
 **** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** * **** */
```
Tested and working fine for me. @tm1000 I will leave to you to merge.

**Comment by themurman** [comment]
Comments added!

**Comment by tm1000** [comment]
@themurman refresh my memory. Did you fill out: http://wiki.freepbx.org/display/DC/Code+License+Agreement

If not you have to fill this out.

**Comment by themurman** [comment]
You should see the form now, I was out of town.

**Comment by themurman** [comment]
Bump.

**Pull request merged**
